### ISSUE TITLE
adopt LinkML

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/datamodel#4]
I think we should use LinkML: https://linkml.io/linkml/intro/overview.html#a-bridge-between-frameworks

This is can be used to collected arguments in favor and against.

**Comment by egonw** [comment]
For example, a chemical compounds could be:

```yaml
id: https://purl.vhp4safety.nl/examples/chemicalCompound
name: chemicalCompound
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
  
classes:
  Compound:
    attributes:
      id_compound:
      lot_number:
      id_cas:
      isomeric_smiles:
      inchi:
```

I am not sure (yet) how to do this info: `{key: yes, ref: Samples}`
